### PR TITLE
Issue #154: Fix relational RoleMapping

### PR DESCRIPTION
**Pull request by josepe36**
when the RoleMapping and Role datasource where linked on mongodb the relational mechanism did not work.
With this fix, the relational is right.
The problem was than the principalId was recorded as a string and not as an ObjectId in the mongo collection RoleMapping.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
This might be a duplicate of https://github.com/strongloop/loopback-datasource-juggler/pull/652? Can you try?

**Comment by josepe36** [comment]
thanks, i ll investigate then i ll get more time.

regards

**Comment by Amir-61** [comment]
@josepe36 I'm closing this PR since it looks like the issue has already been solved by [PR#652](https://github.com/strongloop/loopback-datasource-juggler/pull/652).

Thanks a lot :-)

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Pull request closed without merging**
