### PR TITLE
fix: issue 251

### PR DESCRIPTION
**Pull request by brownman**
https://github.com/strongloop/loopback-connector-mongodb/issues/251

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by 0candy** [comment]
Issue #251 is fixed, closing this PR.

**Pull request closed without merging**
