### PR TITLE
Use ObjectId as internal storage for id

### PR DESCRIPTION
**Pull request by raymondfeng**
See https://github.com/strongloop/loopback-connector-mongodb/issues/208

@jmls @BerkeleyTrue Can you test this PR?

### CODE REVIEW

**Comment by raymondfeng** [comment]
@jmls @BerkeleyTrue Can you confirm before I merge and release?

**Comment by jmls** [comment]
I will try to confirm tonight. I "fixed" my db already, so will have to recreate the scenario

**Comment by raymondfeng** [comment]
I am out of the office until 01/04/2016.

Happy holidays!


Note: This is an automated response to your message  "Re:
[loopback-connector-mongodb] Use ObjectId as internal storage for id
(#210)" sent on 12/21/15 2:46:46 PM.

This is the only notification you will receive while this person is away.

**Comment by BerkeleyTrue** [comment]
Sorry about the late reply. This works for us.

**Pull request merged**
