### PR TITLE
Add support for `nin` to mongodb

### PR DESCRIPTION
**Pull request by 0ff**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by alFReD-NSH** [comment]
This is obsolete now. [`nin` is already supported](https://github.com/strongloop/loopback-connector-mongodb/blob/v1.13.3/lib/mongodb.js#L586-L592)

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
@alFReD-NSH Thanks for looking. Closing this as the feature is already implemented.

**Pull request closed without merging**
