### PR TITLE
Update eslint

### PR DESCRIPTION
**Pull request by Amir-61**
* Update eslint

### CODE REVIEW

**Comment by superkhau** [comment]
LGTM

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@rmg I assume `nvm` machines are not setup yet and I can ignore their failure, is that right? Thanks!

**Comment by rmg** [comment]
@Amir-61 it has mongodb running on it. Perhaps the connection information is not in the expected form, or the version is too new?

**Comment by rmg** [comment]
Ah, found the problem. `cis-jenkins` is actually running the linter. The builds on ci.strongloop.com don't run `npm test` so they don't trigger the `posttest` that does all the linting.

Good news is you should be able to fix this by doing `npm test` locally.

**Pull request closed without merging**
