### PR TITLE
Update juggler3

### PR DESCRIPTION
**Pull request by 0candy**
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/1040

Was trying to commit to this PR (https://github.com/strongloop/loopback-connector-mongodb/pull/283), but ended up creating a new one.

### CODE REVIEW

**Comment by 0candy** [comment]
@slnode test please

**Comment by superkhau** [comment]
LGTM

**Comment by superkhau** [comment]
CI fixes at strongloop/loopback-datasource-juggler#1087

**Comment by 0candy** [comment]
@slnode test please

**Comment by 0candy** [comment]
@slnode test please

**Pull request merged**
