### PR TITLE
Cherry-pick: Resolve issue #540 for v3.9.2

### PR DESCRIPTION
**Pull request by carlos-peru**
### Description
- Cherry-pick #541 

#### Related issue
- #540 

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@slnode test please

**Comment by raymondfeng** [comment]
@carlos-peru Thank you for the patch. Can you investigate the CI failure - https://travis-ci.org/strongloop/loopback-connector-mongodb/builds/604945227?utm_source=github_status&utm_medium=notification?

**Comment by jeemok** [comment]
@carlos-peru did you managed to figure out what's wrong with the build? 

image

**Pull request closed without merging**
