### PR TITLE
feat: add support for new MongoClient options (#389)

### PR DESCRIPTION
**Pull request by mrfelton**
Fix for #389

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
@mrfelton You'll need to sign the CLA before we can review or land your code, please click [this link](https://cla.strongloop.com/agreements/strongloop/loopback-connector-mongodb) to see the terms of the agreement, and sign.

**Comment by kjdelisle** [comment]
@mrfelton Sorry, but we can't accept this pull request without you signing the CLA.

**Pull request closed without merging**
