### PR TITLE
Coerce values of array property defined as ObjectID type

### PR DESCRIPTION
**Pull request by mrbatista**
## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Review by agnes512 — COMMENTED** [review]
Thank you @mrbatista . IIUC, the PR is allowing to have arrays of objectId in where clause? which is different from https://github.com/strongloop/loopback-connector-mongodb/pull/582?

**Review by agnes512 — APPROVED** [review]
👏 🚢

**Comment by mrbatista** [comment]
@agnes512 When release a new version that include this change?

**Comment by mrbatista** [comment]
@dhmlau Please release a new version.
Thanks.

**Comment by dhmlau** [comment]
@mrbatista, `loopback-connector-mongodb@6.0.0` is released.

**Pull request merged**
