### PR TITLE
nin filter map to mongo ObjectId

### PR DESCRIPTION
**Pull request by SSchaaf**
The inq filter maps the data to mongo ObjectId()
This change is to implement the same behaviour to nin filter.

related issue :
https://github.com/strongloop/loopback-connector-mongodb/issues/52

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@SSchaaf Thank you for the patch. Would you please add a test case?

**Comment by SSchaaf** [comment]
@raymondfeng, thanks for loopback, great project. I don't know how to do this. I will take a look and if possible will give a try Raymond,

**Comment by raymondfeng** [comment]
@SSchaaf Try to add a test into https://github.com/strongloop/loopback-connector-mongodb/blob/master/test/mongodb.test.js. It's based on mocha and you should be able to follow the existing ones.

**Comment by SSchaaf** [comment]
@raymondfeng I am using Windows. I don't have nake.exe. So I installed a GNU make but cannot run npm test; ...

```
C:\inetpub\wwwroot\GitHub\loopback-connector-mongodb>npm test

> loopback-connector-mongodb@1.7.0 test C:\inetpub\wwwroot\GitHub\loopback-connector-mongodb
> make test

./node_modules/.bin/mocha -G --timeout 10000 test/*.test.js
'.' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
make: *** [test] Error 1
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

C:\inetpub\wwwroot\GitHub\loopback-connector-mongodb>
```

Another option to run tests in windows ?

**Comment by raymondfeng** [comment]
You can run `mocha --timeout 5000 -R spec`

**Comment by superkhau** [comment]
@SSchaaf Did you ever get around to write a test for this?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by ssh24** [comment]
This PR is not needed anymore. `nin` filter already does that in current [master](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L730). 

Closing the PR as a result.

**Pull request closed without merging**
