### PR TITLE
Fields projection fix

### PR DESCRIPTION
**Pull request by Gonyoda**
### Description
Fix mongodb field projection.  Possibly a regression bug in 3.x driver. See issue #435 
Also eliminate some unnecessary function calls while mapping records.

### Checklist
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@slnode test please

**Comment by Gonyoda** [comment]
@jannyHou I updated the original unit test instead of creating a new one. I believe that the intention of the original test was to verify the mongo result only contained fields you asked for. But since the test was affected by juggler, the test was more or less broken.  So, I modified the original based on your recommendation.

**Comment by Gonyoda** [comment]
Commit linter complained my commit message is too long. Sorry, I didn't see the requirement that commit messages were 50 characters or fewer. Do I really need to shorten my commit message? That means I need to create a new branch and pull request.  Let me know if I need to, thanks.

**Comment by dhmlau** [comment]
@Gonyoda , yes, you'd need to shorten the first sentence in the commit message to 50 characters. Feel free to make it as multiple line.
You can just modify the commit message without creating another branch or PR.  Please see instructions in here: https://help.github.com/articles/changing-a-commit-message/

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@jannyHou , PTAL again.  Once it's merged, I can release. Thanks.

**Pull request merged**
