### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by VusalIs**
I saw some spelling errors while I was reading the README.md file and decided to correct them.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by hacksparrow** [comment]
@VusalIs thanks for the contribution. Can you please sign the CLA - https://cla.strongloop.com/agreements/strongloop/loopback-connector-mongodb?

**Comment by VusalIs** [comment]
> @VusalIs thanks for the contribution. Can you please sign the CLA - https://cla.strongloop.com/agreements/strongloop/loopback-connector-mongodb?

I signed the CLA.

**Comment by hacksparrow** [comment]
Wow. Jenkins still sitting there.

**Comment by agnes512** [comment]
@slnode test please

**Pull request merged**
