### PR TITLE
Add nestedProperty to connectorCapabilities

### PR DESCRIPTION
**Pull request by jannyHou**
Connect to https://github.com/strongloop/loopback/issues/517

Add nestedProperty to connectorCapabilities so loopback-datasource-juggler can read it when deciding test relative features or not.

### CODE REVIEW

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@strongloop/sq-lb-apex Verified that the failure is not related to code. It fails due to no test case in `loopback-example-bluemix`, see issue https://github.com/strongloop/loopback-example-bluemix/issues/2

PTAL again. Thanks.

**Comment by loay** [comment]
@jannyHou 
We need to add the test folder and a unit test within the bluemix repo so the test passes. 
I created this pr to fix the problem: https://github.com/strongloop/loopback-example-bluemix/pull/3

**Comment by loay** [comment]
@slnode test please

**Comment by bugdanov** [comment]
:+1:

**Pull request merged**
