### PR TITLE
Make test instructions more meaningful

### PR DESCRIPTION
**Pull request by superkhau**
Currently blocking test verification for strongloop/loopback#1167 as tests on master are currently failing.

@bajtos @raymondfeng @ritch Am I missing something in these instructions?

Connected to strongloop/loopback#1167

### CODE REVIEW

**Comment by superkhau** [comment]
@slnode test please

**Comment by bajtos** [comment]
@raymondfeng knows how the tests work. In some (most?) connectors you have to put a `.loopbackrc` file with database credentials to your project root and then use our DB instance running in the cloud for the tests.

**Comment by superkhau** [comment]
@bajtos @raymondfeng @ritch Same test instruction updates here. Merging without review.

**Comment by bajtos** [comment]
FWIW, I am using this setup on my machine to test against a local MongoDB instance. Could you please check that it works for you and update the README accordingly?

Contents of ".loopbackrc":

```json
{
  "test": {
    "mongodb": {
      "host": "127.0.0.1"
    }
  }
}
```

**Pull request merged**
