### PR TITLE
Convert foreign keys to ObjectId in where filter

### PR DESCRIPTION
**Pull request by luxigo**
### Description

Convert foreign keys to ObjectId in where filter

#### Related issues

- connect to #395 

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by luxigo** [comment]
... git config issue

**Pull request closed without merging**
