### PR TITLE
Add support for connection string options

### PR DESCRIPTION
**Pull request by acourtiol**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jdrouet** [comment]
:+1:

**Comment by raymondfeng** [comment]
We already have support for mongodb connection string. Just set `url` to `mongodb://...`.

**Comment by acourtiol** [comment]
We can't just set the url in our case and giving users the choice wouldn't hurt. Whatever...

**Comment by raymondfeng** [comment]
@acourtiol Can you elaborate your use case? Maybe an example of config?

**Pull request closed without merging**
