### PR TITLE
Support `ctx.isNewInstance`

### PR DESCRIPTION
**Pull request by bajtos**
Modify the following two DAO methods to report back whether a new
instance was created:

 - updateOrCreate
 - save

Requires https://github.com/strongloop/loopback-datasource-juggler/pull/554

/to @raymondfeng please review

### CODE REVIEW

**Comment by raymondfeng** [comment]
LGTM

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
Strangely enough, [build #74](http://ci.strongloop.com/job/loopback-connector-mongodb.pr/74/) passed on all amazon slaves and failed on all ubuntu slaves.

@rmg what is the difference between these two environment? Is there a different MongoDB version installed?

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
NVM, I diagnosed the problem and added a fixup commit that should add support for older versions too.

**Comment by rmg** [comment]
@slnode test please

**Comment by bajtos** [comment]
> Does the (same) driver return different information depending on the version of mongodb?

Yes, that's my impression.

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
I have reworked the patch to support different MongoDB version (response formats). @raymondfeng PTAL again.

**Comment by raymondfeng** [comment]
LGTM

**Pull request merged**
