### PR TITLE
Validate coordinates existis

### PR DESCRIPTION
**Pull request by eduardoarn**
error in my application

/node_modules/loopback-connector-mongodb/lib/mongodb.js:236
         lat: data [p] .coordinates [1],

TypeError: Cannot read property '1' of undefined

I do not know if my change is the most elegant but the intention would be to validate if there are actually values in the coordinates property

#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by eduardoarn** [comment]
ok

**Comment by eduardoarn** [comment]
.ok\W+to\W+test.

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
@eduardoarn Sorry, I'm working through a whole bunch of items/PRs to triage and so it's taken much longer than I would've liked to get to these.

Would you be able to:

- sign the CLA
- rebase your PR
- change your commit messages to conform to our commit message guide
- add a description to this ticket explaining the purpose of this change
- add test coverage for your changes to validate them, as well as describe their intent via code

**Comment by dhmlau** [comment]
@eduardoarn , are you still interested to work with us in this PR?  If so, could you please address @kjdelisle 's [above comment](https://github.com/strongloop/loopback-connector-mongodb/pull/405#issuecomment-365419233)?  Thanks!

**Pull request closed without merging**
