### PR TITLE
Added documentation on `"authSource"` in connection properties

### PR DESCRIPTION
**Pull request by auguster**
### Description
Added documentation on `"authSource"` in connection properties.

Other changes:
- Replaced `username` to `user` in the connection properties table and datasources example,
- Fixed wierd quotes in json example,
- Added some value highlights to `connector` values.

#### Related issues
- Add mention to "authSource" in Creating a MongoDB data source #468

### Checklist
No test done as this PR is only documentation related.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by auguster** [comment]
I didn't know about the 50 characters restrictions, I have to figure out how to edit them. I'll do that as soon as possible.

**Comment by dhmlau** [comment]
@auguster , you can use `git commit --amend` to modify the commit message.  Details can be found here: https://help.github.com/articles/changing-a-commit-message/.  We can help you with the commit messages if you want. 
More importantly, could you please sign the CLA?  Thanks! https://cla.strongloop.com/agreements/strongloop/loopback-connector-mongodb

**Comment by auguster** [comment]
I signed the CLA and merged my commits.
Thanks for the documentation, it helped a lot.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@auguster , thanks for your contribution.  Your PR has landed!

**Pull request merged**
