### PR TITLE
Merge from master

### PR DESCRIPTION
**Pull request by cloudever**
#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by kjdelisle** [comment]
@cloudever I'm not sure what this pull request is meant to address. Did you open this PR in error?
I'm assuming that it wasn't intended to reach the upstream since you're blanket-disabling a filter function.

If for some reason, this is actually intended to be for the upstream, could you:
- sign the [CLA](https://cla.strongloop.com/agreements/strongloop/loopback-connector-mongodb)
- rebase your PR
- change your commit messages to conform to our [commit message guide](https://loopback.io/doc/en/contrib/git-commit-messages.html)
- add a description to this ticket explaining the purpose of this change

**Comment by dhmlau** [comment]
@cloudever , could you please address the [above questions & requests](https://github.com/strongloop/loopback-connector-mongodb/pull/404#issuecomment-365418444)?  thanks.

**Comment by dhmlau** [comment]
Closing as abandoned.

**Pull request closed without merging**
