### PR TITLE
Check dataSource.connecting to prevent race conditions

### PR DESCRIPTION
**Pull request by fabien**
See issue: #220 

/cc @raymondfeng

### CODE REVIEW

**Comment by superkhau** [comment]
LGTM but I'll leave it for @raymondfeng for the final merge.

**Comment by fabien** [comment]
@superkhau @raymondfeng ping

**Comment by superkhau** [comment]
@slnode test please.

**Comment by fabien** [comment]
@superkhau another ping, sorry ...

**Comment by superkhau** [comment]
@raymondfeng Got no response from you, I'm gonna merge this since it passes CI.

**Comment by superkhau** [comment]
@fabien Merged. Thanks for the contribution. ;)

**Pull request merged**
