### PR TITLE
Added unit tests

### PR DESCRIPTION
**Pull request by djdrisco**
To demonstrate that the connector does support querying for embedded documents

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
ok to test

**Comment by raymondfeng** [comment]
ok to test

**Comment by 0candy** [comment]
@djdrisco Could you please rebase this PR or grant me permission to collaborate to update it? Thanks!

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@djdrisco Thank you for the contribution. Could you please rebase your branch? Please be aware that [./test/mongodb.test.js](https://github.com/djdrisco/loopback-connector-mongodb/blob/master/test/mongodb.test.js) file will have merge conflicts.

**Comment by ssh24** [comment]
Closing this PR as there has been no activity on it and we currently have test coverage for embedded documents.

**Pull request closed without merging**
