### PR TITLE
update the near query with minDistance test since minDistance is supported

### PR DESCRIPTION
**Pull request by wenwei1202**
### Description
Update the near query with minDistance test since the minDistance option is supported in loopback-datasource-juggler.
#### Related issues

- None

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
CI is failing because the test for `minDistance` had to be updated before landing https://github.com/strongloop/loopback-datasource-juggler/pull/987.

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@wenwei1202 PR is ready to land. Thank you for the contribution!

**Pull request merged**
