### PR TITLE
coerce property value defined as array of ObjectID

### LINKED ISSUE #537: referencesMany relation causes "is not an ObjectId string" error.
Hello,

I have a referencesMany relation in one of my models, and since v5.0.0 I cannot create a new object from this model, but it works perfectly fine with v4.2.0. The relation is this:

"foods": {
  "type": "referencesMany",
  "model": "Food",
  "foreignKey": "foodIds",
  "options": {
    "validate": true,
    "forceId": false
  }
}

When i delete this relation, i can create an object from this model without an error, but now i get the following error:

Error:  is not an ObjectID string
at coerceToObjectId (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-connector-mongodb\lib\mongodb.js:1915:13)
at coercePropertyValue (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-connector-mongodb\lib\mongodb.js:2108:17)
at visitAllProperties (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-connector-mongodb\lib\mongodb.js:2072:7)
at MongoDB.toDatabase (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-connector-mongodb\lib\mongodb.js:424:5)
at MongoDB.create (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-connector-mongodb\lib\mongodb.js:576:15)
at invokeConnectorMethod (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\dao.js:172:21)
at C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\dao.js:445:11
at doNotify (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
at doNotify (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
at doNotify (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
at doNotify (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
at doNotify (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:155:49)
at Function.ObserverMixin._notifyBaseObservers (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:178:5)
at Function.ObserverMixin.notifyObserversOf (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:153:8)
at Function.ObserverMixin._notifyBaseObservers (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:176:15)
at Function.ObserverMixin.notifyObserversOf (C:\Users\Dell\Developer\dimp-core\node_modules\loopback-datasource-juggler\lib\observer.js:153:8)

### PR DESCRIPTION
**Pull request by mrbatista**
Fixes #537 

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-connector-mongodb) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by mrbatista** [comment]
CI errors is not related to my changes

**Comment by mrbatista** [comment]
Any update to merge this PR?

**Comment by mrbatista** [comment]
ping @emonddr @jannyHou @b-admike @dhmlau @bajtos @raymondfeng

**Comment by dhmlau** [comment]
Thanks for the reminder, @mrbatista. Your PR has landed. Thanks for your contribution! 🎉

**Pull request merged**
