### PR TITLE
mongodb version locked to 2.2.22

### PR DESCRIPTION
**Pull request by vshushkov**
#### Related issues

strongloop/loopback-connector-mongodb#344

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by gsarfati** [comment]
please 👍

**Comment by jannyHou** [comment]
@vshushkov Thank you for the pr while we already have a fix checked in and released:
https://github.com/strongloop/loopback-connector-mongodb/pull/348

Please update to loopback-connector-mongodb@3.0.1 or loopback-connector-mongodb@1.18.1 to get the latest release :)

**Comment by jannyHou** [comment]
I am closing this pr due to fix https://github.com/strongloop/loopback-connector-mongodb/pull/348
Thanks for understanding.
Feel free to reopen it if you have further questions.

**Pull request closed without merging**
