### PR TITLE
Clarkorz feature/optmized find or create

### PR DESCRIPTION
**Pull request by raymondfeng**

### CODE REVIEW

**Comment by raymondfeng** [comment]
@clarkorz There are a few tests failing on mongodb 2.x. See:
1) mongodb imported features relations hasOne with non standard id can be used to query data:
     Uncaught TypeError: Cannot read property 'accid' of null
      at lib/mongodb.js:627:7
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)

  2) Persistence hooks PersistedModel.findOrCreate triggers `access` hook:
     MongoError: Mod on _id not allowed
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)

  3) Persistence hooks PersistedModel.findOrCreate triggers `before save` hook when found:
     MongoError: Mod on _id not allowed
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)

  4) Persistence hooks PersistedModel.findOrCreate triggers `before save` hook when not found:
     MongoError: Mod on _id not allowed
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)

  5) Persistence hooks PersistedModel.findOrCreate triggers hooks in the correct order when not found:
     MongoError: Mod on _id not allowed
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)

  6) Persistence hooks PersistedModel.findOrCreate triggers `after save` hook when not found:
     MongoError: Mod on _id not allowed
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)

  7) Persistence hooks PersistedModel.findOrCreate does not trigger `after save` hook when found:
     MongoError: Mod on _id not allowed
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)

**Comment by clarkorz** [comment]
@raymondfeng what minor version of mongodb that fails these tests? I have tried mongodb 2.6.10 and all tests pass.

I'll try 2.4 and 2.2 tomorrow.

**Comment by clarkorz** [comment]
@raymondfeng This PR requires mongodb 2.6.x and above.

All the failed tests are caused by this [issue](https://jira.mongodb.org/browse/SERVER-9958): `$setOnInsert` doesn't accept `_id` field until mongodb 2.6.0. And this is the only possible approach, as far as I know.

**Comment by raymondfeng** [comment]
Let's make the test conditional using the same trick as https://github.com/strongloop/loopback-connector-mongodb/blob/master/test/mongodb.test.js#L527-L534

**Comment by clarkorz** [comment]
@raymondfeng these tests are imported from juggler. The trick must be used there. And if developer DOES use mongodb 2.4 and call `findOrCreate` with customized id field, it will crash.

Another idea is: read version in `serverStatus()` from mongodb after client created, if version >= 2.6 then define `findOrCreate` else connector won't support this feature. Through?

**Comment by raymondfeng** [comment]
I checked `serverStatus()` before but it requires `admin` access.

**Comment by paran01d** [comment]
Is there any precedent for making this a configuration parameter like at the datasource definition level ? Perhaps that would be an acceptable solution ? (with the default being off).

**Pull request merged**
