### PR TITLE
Convert embedded binary properties to buffer

### PR DESCRIPTION
**Pull request by ntsekouras**
### Description
At the conversion of the data from database to JSON only the top level properties where checked for being binary and converted to buffer.
I added a check for a property if is an embedded model and used recursion to loop through these models' properties

#### Related issues
- connect to [#470](https://github.com/strongloop/loopback-connector-mongodb/issues/470)

### Checklist
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@slnode test please

**Comment by bajtos** [comment]
Landed 🎉  Thank you @ntsekouras for your first contribution! ❤️

**Comment by ntsekouras** [comment]
Thank you guys

**Pull request merged**
