### PR TITLE
Add mongo qa test server

### PR DESCRIPTION
**Pull request by cgole**

### CODE REVIEW

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
The patch LGTM. I'll give @raymondfeng few days to comment and if he does not comes back then I'll land this.

@cgole could you please rebase your patch on top of the current master branch?

**Comment by superkhau** [comment]
+1 LGTM

**Comment by bajtos** [comment]
Weird. AFAICT, this was already landed by @superkhau via #203 and by @cgole via de7258a.

**Pull request closed without merging**
