### PR TITLE
Include tests of persistence hooks from juggler

### PR DESCRIPTION
**Pull request by bajtos**
Connect: https://github.com/strongloop/loopback-datasource-juggler/issues/367

Requires #87 and https://github.com/strongloop/loopback-datasource-juggler/pull/422

/to @raymondfeng please review

### CODE REVIEW

**Comment by raymondfeng** [comment]
LGTM

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
I cannot merge this patch until #87 is fixed. 

Note that `eql` in `should@1.3.0` treats `undefined` and `null` values as the same, which explains why this patch can pass the tests in certain scenarios.

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
The tests are passing on Amazon slaves, failing on Ubuntu slaves. /cc @rmg @raymondfeng 

I'll assume the problem is not in this patch.

**Comment by rmg** [comment]
@bajtos I didn't look at the failures, but could it be related to the Ubuntu VMs running MongoDB 2.4.x and the AWS VM's running MongoDB 2.6.x? I recently add an environment variable to our CI that gives the version of mongodb in `$MONGODB_VERSION` so that tests dependant on the version can be skipped if necessary.

**Comment by bajtos** [comment]
>  could it be related to the Ubuntu VMs running MongoDB 2.4.x and the AWS VM's running MongoDB 2.6.x? I recently add an environment variable to our CI that gives the version of mongodb in $MONGODB_VERSION so that tests dependant on the version can be skipped if necessary.

@raymondfeng Could you PTAL? I am not familiar with the tests in this repo.

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-connector-mongodb/pull/91

**Pull request merged**
