### PR TITLE
Resolve issue #540 for v4.2.0

### PR DESCRIPTION
**Pull request by herbertscruz**
Resolve issue #540 for v4.2.0

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@herbertscruz , thanks for your PR.  Could you please add tests for your changes? Thanks.

**Comment by herbertscruz** [comment]
> @herbertscruz , thanks for your PR. Could you please add tests for your changes? Thanks.

@dhmlau, thanks for reviewing. This PR is just adding configuration parameters in mongodb connect, I don't know how I could implement unit tests just in case.

Any suggestion?

**Comment by dhmlau** [comment]
@herbertscruz , I'm thinking to have a similar test for `allowExtendedOperators`, see https://github.com/strongloop/loopback-connector-mongodb/blob/c5200e26498ffcd2b560e3a3cf8ba2795bbf603f/test/mongodb.test.js#L1255.

What do you think?

**Pull request merged**
