### PR TITLE
Show illegal unescaped password error on console

### PR DESCRIPTION
**Pull request by alejandrochvs**
When the password contains an illegal unescaped character there is no indication that the problem is that, this should indicate the problem and handle the exception

#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by hacksparrow** [comment]
We plan to handle the encoding - https://github.com/strongloop/loopback-connector-mongodb/pull/527

**Comment by hacksparrow** [comment]
Thanks for the PR @alejandrochvs. Since we have closed https://github.com/strongloop/loopback-connector-mongodb/pull/527, let's consider this PR.

@bajtos @b-admike @jannyHou how do you suggest we handle this case?

In automated remote environments, `console.log()` may not help. Should the app continue to start with invalid creds or exit with a code?

**Comment by hacksparrow** [comment]
If there is an encoding problem in the username or password, the whole error stack is printed on the console and the app will not start.

I don't think, we should do anything more. @alejandrochvs do let me know, if I misunderstood anything.

**Pull request closed without merging**
