### PR TITLE
Convert foreign keys to ObjectId in where filter

### PR DESCRIPTION
**Pull request by luxigo**
### Description

Convert foreign keys to ObjectId in where filter

#### Related issues

- connect to #395 

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by kjdelisle** [comment]
@luxigo Some of your commit messages violate our commit rules. Would you be able to rebase your PR to shorten the commit titles?

See http://loopback.io/doc/en/contrib/code-contrib.html (and more specifically, http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) for details.

@slnode test please

**Pull request closed without merging**
